---
galaxy_info:
  role_name: kubelet_kubectl
  author: azunetes
  description: Install kubelet and kubectl on Debian 13 Trixie nodes.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions: ["all"]
dependencies:
  - role: kubernetes_apt_repo
