---
galaxy_info:
  author: azuki774
  description: Containerd runtime bootstrap for azunetes
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
