---
- name: Apply common host settings
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: common

- name: Install Kubernetes base components (kubelet / kubectl)
  hosts:
    - controlplane
    - worker
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: kubernetes_apt_repo
    - ansible.builtin.meta: flush_handlers
    - ansible.builtin.include_role:
        name: kubelet_kubectl

- name: Install kubeadm on control plane nodes
  hosts: controlplane
  become: true
  tasks:
    - ansible.builtin.include_role:
        name: kubernetes_apt_repo
    - ansible.builtin.meta: flush_handlers
    - ansible.builtin.include_role:
        name: kubeadm
