---
- name: Check if calicoctl is already installed with correct version
  ansible.builtin.command:
    argv:
      - "{{ calicoctl_binary_path }}"
      - version
  register: calicoctl_current_version
  changed_when: false
  failed_when: false

- name: Download calicoctl binary
  ansible.builtin.get_url:
    url: "{{ calicoctl_download_url }}"
    dest: "{{ calicoctl_binary_path }}"
    mode: "0755"
    checksum: "{{ calicoctl_checksum }}"
  when: >
    calicoctl_current_version.rc != 0 or
    calicoctl_version not in (calicoctl_current_version.stdout | default(''))
